# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
