# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventalinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
