# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20171105_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/imagenes'),
        ),
    ]
